SELECT 
    '액션' as GEN,
    SUM(SUM_TOTAL_PLAYTIME)/SUM(COUNT_GAME_ID) as SUM_TOTAL_PLAYTIME,
    SUM(SUM_LAST_TWO_WEEKS_PLAYTIME)/SUM(COUNT_GAME_ID) as SUM_LAST_TWO_WEEKS_PLAYTIME
    FROM ANALYTICS_DATA.GAME_AVERAGE_DASHBOARD
    GROUP BY 1
UNION ALL
SELECT 
    '어드벤처' as GEN,
    SUM(SUM_TOTAL_PLAYTIME)/SUM(COUNT_GAME_ID) as SUM_TOTAL_PLAYTIME,
    SUM(SUM_LAST_TWO_WEEKS_PLAYTIME)/SUM(COUNT_GAME_ID) as SUM_LAST_TWO_WEEKS_PLAYTIME
    FROM ANALYTICS_DATA.GAME_AVERAGE_DASHBOARD
    WHERE GENRE LIKE '%어드벤처%'
    GROUP BY 1
UNION ALL
SELECT 
    'MULTI' as GEN,
    SUM(SUM_TOTAL_PLAYTIME)/SUM(COUNT_GAME_ID) as SUM_TOTAL_PLAYTIME,
    SUM(SUM_LAST_TWO_WEEKS_PLAYTIME)/SUM(COUNT_GAME_ID) as SUM_LAST_TWO_WEEKS_PLAYTIME
    FROM ANALYTICS_DATA.GAME_AVERAGE_DASHBOARD
    WHERE GENRE LIKE '%대규모멀티플레이어%'
    GROUP BY 1
UNION ALL
SELECT 
    'RPG' as GEN,
    SUM(SUM_TOTAL_PLAYTIME)/SUM(COUNT_GAME_ID) as SUM_TOTAL_PLAYTIME,
    SUM(SUM_LAST_TWO_WEEKS_PLAYTIME)/SUM(COUNT_GAME_ID) as SUM_LAST_TWO_WEEKS_PLAYTIME
    FROM ANALYTICS_DATA.GAME_AVERAGE_DASHBOARD
    WHERE GENRE LIKE '%RPG%'
    GROUP BY 1
UNION ALL
SELECT 
    '캐주얼' as GEN,
    SUM(SUM_TOTAL_PLAYTIME)/SUM(COUNT_GAME_ID) as SUM_TOTAL_PLAYTIME,
    SUM(SUM_LAST_TWO_WEEKS_PLAYTIME)/SUM(COUNT_GAME_ID) as SUM_LAST_TWO_WEEKS_PLAYTIME
    FROM ANALYTICS_DATA.GAME_AVERAGE_DASHBOARD
    WHERE GENRE LIKE '%캐주얼%'
    GROUP BY 1
UNION ALL
SELECT 
    '인디' as GEN,
    SUM(SUM_TOTAL_PLAYTIME)/SUM(COUNT_GAME_ID) as SUM_TOTAL_PLAYTIME,
    SUM(SUM_LAST_TWO_WEEKS_PLAYTIME)/SUM(COUNT_GAME_ID) as SUM_LAST_TWO_WEEKS_PLAYTIME
    FROM ANALYTICS_DATA.GAME_AVERAGE_DASHBOARD
    WHERE GENRE LIKE '%인디%'
    GROUP BY 1
UNION ALL
SELECT 
    '전략' as GEN,
    SUM(SUM_TOTAL_PLAYTIME)/SUM(COUNT_GAME_ID) as SUM_TOTAL_PLAYTIME,
    SUM(SUM_LAST_TWO_WEEKS_PLAYTIME)/SUM(COUNT_GAME_ID) as SUM_LAST_TWO_WEEKS_PLAYTIME
    FROM ANALYTICS_DATA.GAME_AVERAGE_DASHBOARD
    WHERE GENRE LIKE '%전략%'
    GROUP BY 1
UNION ALL
SELECT 
    '시뮬레이션' as GEN,
    SUM(SUM_TOTAL_PLAYTIME)/SUM(COUNT_GAME_ID) as SUM_TOTAL_PLAYTIME,
    SUM(SUM_LAST_TWO_WEEKS_PLAYTIME)/SUM(COUNT_GAME_ID) as SUM_LAST_TWO_WEEKS_PLAYTIME
    FROM ANALYTICS_DATA.GAME_AVERAGE_DASHBOARD
    WHERE GENRE LIKE '%시뮬레이션%'
    GROUP BY 1
UNION ALL
SELECT 
    '스포츠' as GEN,
    SUM(SUM_TOTAL_PLAYTIME)/SUM(COUNT_GAME_ID) as SUM_TOTAL_PLAYTIME,
    SUM(SUM_LAST_TWO_WEEKS_PLAYTIME)/SUM(COUNT_GAME_ID) as SUM_LAST_TWO_WEEKS_PLAYTIME
    FROM ANALYTICS_DATA.GAME_AVERAGE_DASHBOARD
    WHERE GENRE LIKE '%스포츠%'
    GROUP BY 1
UNION ALL
SELECT 
    '레이싱' as GEN,
    SUM(SUM_TOTAL_PLAYTIME)/SUM(COUNT_GAME_ID) as SUM_TOTAL_PLAYTIME,
    SUM(SUM_LAST_TWO_WEEKS_PLAYTIME)/SUM(COUNT_GAME_ID) as SUM_LAST_TWO_WEEKS_PLAYTIME
    FROM ANALYTICS_DATA.GAME_AVERAGE_DASHBOARD
    WHERE GENRE LIKE '%레이싱%'
    GROUP BY 1